version: '3.8'

services: 
    myavtask:
      build: ./
      command: ./avtask
      ports:
        - 8080:8000
      depends_on: 
        -db
      environment: 
        DB_PASSWORD=pass 

    db:
      image: postgres:12.2-alpine
      container_name: "database"
      ports: 
        -"5432:5432"
      environment: 
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres